server:
   port: 11003
   servlet:
      contextPath: /qa-tool
      
spring:
   datasource:
      url: jdbc:oracle:thin:@localhost:1521:qa
      database: qa
      user: qa
      password: qa
      driver-class-name: oracle.jdbc.driver.OracleDriver
   liquibase:
      changeLog: classpath:config/liquibase/db-changelog.xml
      url: jdbc:oracle:thin:@localhost:1521:qa
      user: qa
      password: qa
   jpa:
      database-platform: org.hibernate.dialect.Oracle12cDialect
      properties:
         hibernate:
            temp:
               use_jdbc_metadata_defaults: false
      hibernate:
         ddl-auto: none
   hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      
application:
   flavor: angular
   version: 0.0.1